test_generation:
  framework: drogon
  test_location: "./test"
  test_naming_convention: "test_{controller}_{action}.cc"
  coverage:
    - controllers
    - models
    - services
  assertions:
    - response_code
    - response_body
    - error_handling
  test_cases:
    - positive_cases: true
    - negative_cases: true
    - edge_cases: true
  generate_mocks: true
llm:
  prompt_style: strict
  temperature: 0.2
tests:
  coverage_threshold: 80
  ignore_patterns:
    - "**/*.mock.h"
  require_assertions: true